// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ampcrequlfclkxzgdsas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtcGNyZXF1bGZjbGt4emdkc2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTAwMDEsImV4cCI6MjA3MjI2NjAwMX0.27wKnuoiyW2gfqv4JMuy4qqzHqQU9Te41ZP_uywse7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});